{% if name_suffix is not defined %}
{% set name_suffix = "3.9" %}
{% endif %}
{% set name = "pypy" ~ name_suffix %}

package:
  name: {{ name }}
  version: 7.3.11  # [name_suffix == "3.8"]
  version: 7.3.12  # [name_suffix == "3.9"]

source:
  - folder: pypy3
    url: https://downloads.python.org/pypy/{{ name }}-v7.3.11-src.tar.bz2  # [name_suffix == "3.8"]
    url: https://downloads.python.org/pypy/{{ name }}-v7.3.12-src.tar.bz2  # [name_suffix == "3.9"]
    sha256: 4d6769bfca73734e8666fd70503b7ceb06a6e259110e617331bb3899ca4e6058  # [name_suffix == "3.8"]
    sha256: e7a2046c7e6c25fc386abbb5132e92a7cc2491e3935699a946cb5dcbb342c2aa  # [name_suffix == "3.9"]
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/tk_app.patch
      - patches/lzma_build.patch  # [win]
      - patches/clibffi.patch     # [osx]
      - patches/darwin.patch      # [osx and name_suffix == "3.8"]
      - patches/0001-Add-conda-forge-version.patch
      - patches/0021-Adapt-platform-to-patch-0001.patch
      - patches/0023a-Fix-LIBDIR.patch  # [name_suffix=="3.8"]
      - patches/0023b-Fix-LIBDIR.patch  # [name_suffix=="3.9"]
      - patches/0030-Swap-libffi8-for-7.patch
      # Patches by @mingwandroid from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0024-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      # Patches for 3.8 only
      - patches/0019-Disable-copying-dlls.patch  # [name_suffix == "3.8"]
      - patches/0020-Use-private-attribute-in-datetime_delta.patch  # [name_suffix == "3.8"]
      - patches/0031-Fix-pthread_t-casting.patch  # [name_suffix == "3.8"]
      - patches/0032-Copy-dependent-libs-for-venvs.patch
      # Patches after 7.3.12
      - patches/pypy_107654.patch
      - patches/pypy_107655.patch
      - patches/pypy_107656.patch
      - patches/pypy_107657.patch
      - patches/pypy_107658.patch
      - patches/pypy_107659.patch  # [name_suffix == "3.9"]
      - patches/pypy_107663.patch  # [name_suffix == "3.8"]
      - patches/pypy_107660.patch  # [name_suffix == "3.9"]
      - patches/pypy_107661.patch
      - patches/pypy_107668.patch  # [name_suffix == "3.9"]


  - url: https://downloads.python.org/pypy/pypy2.7-v7.3.6-win64.zip           # [win]
    sha256: fcc8f6b3b472a77eaa754951f288fe234b4953bfba845888dd839b9b862cb891  # [win]
    folder: pypy2-binary                                                      # [win]

build:
  number: 5
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3   # [not win]
    - pkg-config        # [unix]
    - pycparser
    - expat
  host:
    - bzip2
    - expat
    - gdbm     # [not win]
    - jom ==1.1.2  # [win]
    - libffi
    - make     # [linux]
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xorg-libx11  # [linux]
    - xz
    - zlib
    - tzdata   # [name_suffix != "3.8"]
  run:
    - bzip2
    - expat
    - gdbm     # [not win]
    - libffi
    - ncurses  # [not win]
    - openssl
    - sqlite
    - tk
    - xz
    - zlib
    - tzdata   # [name_suffix != "3.8"]
  run_constrained:
    - pypy3.5 ==99999999999
    - pypy3.6 ==99999999999
    - pypy3.7 ==99999999999
    - pypy3.8 ==99999999999  # [name_suffix=="3.9"]
    - pypy3.9 ==99999999999  # [name_suffix=="3.8"]
    - python {{ name_suffix }}.* *_73_pypy

test:
  commands:
    - pypy3 --help
    - pypy3 -c "import platform; print(platform._sys_version())"
    - pypy3 -c "import tkinter; tkinter.Tk()"                                                    # [not unix]
    - test -f $PREFIX/lib/pypy{{ name_suffix }}/lib2to3/Grammar{{ name_suffix }}*.pickle         # [unix]
    - test -f $PREFIX/lib/pypy{{ name_suffix }}/lib2to3/PatternGrammar{{ name_suffix }}*.pickle  # [unix]
    - if not exist %PREFIX%\lib\lib2to3\Grammar{{ name_suffix }}*.pickle exit 1                  # [win]
    - if not exist %PREFIX%\lib\lib2to3\PatternGrammar{{ name_suffix }}*.pickle exit 1           # [win]
    - pypy3 -m test.test_ssl
    # make sure Scripts dir exists so downstream entry_points are created successfully
    - if not exist %PREFIX%\Scripts\ exit 1  # [win]
    # Check that zoneinfo works from Python 3.9 onwards, see upstream issue: https://foss.heptapod.net/pypy/pypy/-/issues/3653
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"  # [name_suffix!="3.8"]

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: >
        PyPy is a Python interpreter and just-in-time compiler. See
        https://conda-forge.org/blog/posts/2020-03-10-pypy for more information
        about using PyPy in conda

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
    - mattip
